AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  stage:
    Type: String
    Description: Deployment stage (dev, stage, prod)
    AllowedValues:
      - dev
      - stage
      - prod

Mappings:
  StreamNames:
    default:
      GoogleAccount: google-account
      GoogleAccountLog: google-account-log
      GoogleAd: google-ad
      GoogleAdLog: google-ad-log
      GoogleCampaign: google-campaign
      GoogleCampaignLog: google-campaign-log
      GoogleAdGroup: google-ad-group
      GoogleAdGroupLog: google-ad-group-log
      GoogleAsset: google-asset
      GoogleAssetLog: google-asset-log
      GoogleAssetSet: google-asset-set
      GoogleAssetSetLog: google-asset-set-log
      GoogleFeed: google-feed
      GoogleFeedLog: google-feed-log
      GoogleFeedItem: google-feed-item
      GoogleFeedItemLog: google-feed-item-log
      GoogleKeyword: google-keyword
      GoogleKeywordLog: google-keyword-log
      GoogleSharedSet: google-shared-set
      GoogleSharedSetKeyword: google-shared-set-keyword
      GoogleSharedSetLog: google-shared-set-log
      GoogleSharedSetKeywordLog: google-shared-set-keyword-log

  Layers:
    stage:
      GoogleAdsLayer: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:google-ads-layer:4"
      BingAdsLayer: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:bing-ads-layer:4"
    prod:
      GoogleAdsLayer: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:google-ads-layer:2"
      BingAdsLayer: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:bing-ads-layer:2"
    dev:
      GoogleAdsLayer: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:google-ads-layer:1"
      BingAdsLayer: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:bing-ads-layer:1"

Resources:
  GoogleAdsEditorFeedItemLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub googleAdsEditorFeedItemV1
      Description: Updates Google Ads Feed Items
      Handler: feed_item_lambda.handler
      Runtime: python3.13
      CodeUri: ./src
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - GoogleAdsEditorRole
          - Arn
      Timeout: 900
      Environment:
        Variables:
          DEBUG: !Sub ${debug}
          GOOGLE_ADS_REFRESH_TOKEN: !Sub ${googleAdsRefreshToken}
          GOOGLE_ADS_CLIENT_ID: !Sub ${googleAdsClientId}
          GOOGLE_ADS_CLIENT_SECRET: !Sub ${googleAdsClientSecret}
          GOOGLE_ADS_DEVELOPER_TOKEN: !Sub ${googleAdsDeveloperToken}
          GOOGLE_ADS_LOGIN_CUSTOMER_ID: !Sub ${googleAdsLoginCustomerId}
          GOOGLE_ADS_USE_PROTO_PLUS: true
          GOOGLE_SHARED_SET_KEYWORD_LOG: !FindInMap [StreamNames, default, GoogleSharedSetKeywordLog]
      Layers:
        - !Sub ${!FindInMap [Layers, !Ref stage, GoogleAdsLayer]}
        - !Sub ${!FindInMap [Layers, !Ref stage, BingAdsLayer]}

  GoogleAdsEditorSharedSetKeywordLogFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !FindInMap [StreamNames, default, GoogleSharedSetKeywordLog]
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: arn:aws:s3:::data.ihsadvantage
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Sub /aws/kinesisfirehose/${FindInMap [StreamNames, default, GOOGLE_SHARED_SET_KEYWORD_LOG]}
          LogStreamName: S3Delivery
        CompressionFormat: GZIP
        ErrorOutputPrefix: 'json/errors/google/shared-set-keyword-log/error_type=!{firehose:error-output-type}/partition_date=!{timestamp:yyyy}-!{timestamp:MM}-!{timestamp:dd}/'
        Prefix: 'json/google/shared-set-keyword-log/partition_date=!{timestamp:yyyy}-!{timestamp:MM}-!{timestamp:dd}/'
        RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/firehose_delivery_role'
