AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Description: Python Lambda Layers StackSet

Parameters:
  stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod

Resources:
  BingAdsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: !Sub "hotel-planner-deploy-${AWS::AccountId}-${AWS::Region}"
        S3Key: !Sub "bing-ads-layer.zip"
      Description: "Lambda layer containing the python library for Bing Ads."
      LayerName: !Sub "bing-ads-layer"
      LicenseInfo: MIT

  GoogleAdsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: !Sub "hotel-planner-deploy-${AWS::AccountId}-${AWS::Region}"
        S3Key: !Sub "google-ads-layer.zip"
      Description: "Lambda layer containing the python library for Google Ads."
      LayerName: !Sub "google-ads-layer"
      LicenseInfo: MIT

  PytzLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: !Sub "hotel-planner-deploy-${AWS::AccountId}-${AWS::Region}"
        S3Key: !Sub "pytz-layer.zip"
      Description: "Lambda layer containing the python library for PYTZ."
      LayerName: !Sub "pytz-layer"
      LicenseInfo: MIT

Outputs:
  GoogleAdsLayerArn:
    Description: ARN for the Google Ads Lambda Layer
    Value: !Ref GoogleAdsLayer

  BingAdsLayerArn:
    Description: ARN for the Bing Ads Lambda Layer
    Value: !Ref BingAdsLayer

  PytzLayerArn:
    Description: ARN for the Pytz Lambda Layer
    Value: !Ref PytzLayer
