AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Description: Optimized Python Lambda Layers StackSet

Resources:
  BingAdsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.13
      Content:
        S3Bucket: !Sub 'hotel-planner-deploy-${AWS::AccountId}-${AWS::Region}'
        S3Key: bing-ads-layer.zip
      Description: "Lambda layer containing the python library for Bing Ads."
      LayerName: !Sub '${AWS::StackName}-bing-ads-layer'
      LicenseInfo: MIT

  GoogleAdsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.13
      Content:
        S3Bucket: !Sub 'hotel-planner-deploy-${AWS::AccountId}-${AWS::Region}'
        S3Key: google-ads-layer.zip
      Description: "Lambda layer containing the python library for Google Ads."
      LayerName: !Sub '${AWS::StackName}-google-ads-layer'
      LicenseInfo: MIT

Outputs:
  GoogleAdsLayerArn:
    Description: ARN for the Google Ads Lambda Layer
    Value: !Ref GoogleAdsLayer

  BingAdsLayerArn:
    Description: ARN for the Bing Ads Lambda Layer
    Value: !Ref BingAdsLayer
