name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: |
      github.actor == 'github-actions[bot]' && 
      contains(github.head_ref, 'version-bump') && 
      github.event.pull_request.title == 'chore(release): Version bump'
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
