name: Deploy Lambda Layers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Build and Upload Python 2.7 Layers
        run: |
          for req in requirements/pandas.txt requirements/numpy.txt requirements/scikit-learn.txt requirements/pyarrow.txt; do
            pkg=$(basename $req .txt)
            ./deploy-layer.sh $pkg
          done

      - name: Build and Upload Python 3.11 Layers
        run: |
          for req in requirements/google-ads.txt; do
            pkg=$(basename $req .txt)
            ./deploy-layer-3.sh $pkg
          done

      - name: Build and Upload Python 3.12 Layers
        run: |
          for req in requirements/pytz.txt requirements/simplejson.txt; do
            pkg=$(basename $req .txt)
            ./deploy-layer.sh $pkg
          done

      - name: Package CloudFormation Template
        run: |
          aws cloudformation package \
            --template-file lambda-layers-stackset.yaml \
            --output-template-file lambda-layers-stackset-output.yaml \
            --s3-bucket ihs-deploy \
            --s3-prefix cloudformation

      - name: Upload Template to StackSets Bucket
        run: |
          aws s3 cp lambda-layers-stackset-output.yaml s3://ihs-deploy/stacksets/python-lambda-layers.yml

      - name: Update StackSet
        run: |
          aws cloudformation update-stack-set \
            --stack-set-name python-lambda-layers \
            --template-url https://s3.amazonaws.com/ihs-deploy/stacksets/python-lambda-layers.yml \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --permission-model SERVICE_MANAGED \
            --auto-deployment Enabled=true,RetainStacksOnAccountRemoval=false \
            --operation-preferences RegionConcurrencyType=PARALLEL,MaxConcurrentPercentage=100 \
            --regions us-east-1 \
            --parameter-overrides \
              ParameterKey=TargetEnvironment,ParameterValue=production \
              ParameterKey=TargetRegion,ParameterValue=us-east-1
