name: Deploy Lambda Layer/Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  DEFAULT_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev') }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.DEFAULT_REGION }}
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run Tests
        run: npm test
        env:
          npm_config_skiptests: ${{ github.event.inputs.environment == 'prod' && 'false' || 'true' }}
          
      - name: Deploy Stack
        run: npm run deploy
        env:
          npm_package_config_env: ${{ github.event.inputs.environment || (github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'stage' || 'dev') }}
          npm_package_config_accounts: ${{ vars.TARGET_ACCOUNTS }}
          npm_package_config_regions: ${{ vars.TARGET_REGIONS }}
