name: Deploy Lambda Layers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create build directories
        run: |
          mkdir -p dist
          chmod +x scripts/build-layer.sh

      - name: Build Layers
        run: |
          ./scripts/build-layer.sh bingads
          ./scripts/build-layer.sh google-ads

      - name: Upload Layer Packages to S3
        run: |
          aws s3 cp dist/bingads-layer.zip "s3://${AWS_BUCKET}/bingads-layer.zip"
          aws s3 cp dist/google-ads-layer.zip "s3://${AWS_BUCKET}/googleads-layer.zip"
        env:
          AWS_BUCKET: ${{ vars.LAYERS_BUCKET_NAME }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file lambda-layers.yaml \
            --stack-name advertising-sdk-layers \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LayerNamePrefix=advertising-sdk

      - name: Upload Template to StackSets Bucket
        run: |
          aws s3 cp lambda-layers-stackset-output.yaml s3://ihs-deploy/stacksets/python-lambda-layers.yml

      - name: Update StackSet
        run: |
          aws cloudformation update-stack-set \
            --stack-set-name python-lambda-layers \
            --template-url https://s3.amazonaws.com/ihs-deploy/stacksets/python-lambda-layers.yml \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --permission-model SERVICE_MANAGED \
            --auto-deployment Enabled=true,RetainStacksOnAccountRemoval=false \
            --operation-preferences RegionConcurrencyType=PARALLEL,MaxConcurrentPercentage=100 \
            --regions us-east-1 \
            --parameter-overrides \
              ParameterKey=TargetEnvironment,ParameterValue=production \
              ParameterKey=TargetRegion,ParameterValue=us-east-1
