name: Stage - CloudFormation StackSet Deployment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_ADMIN_ACCOUNT_ID: ${{ vars.AWS_ADMIN_ACCOUNT_ID }}
  AWS_DEPLOYMENT_REGION: "us-east-1"
  AWS_DEPLOYMENT_ROLE_ARN: "arn:aws:iam::275193884268:role/github-automations-role-dev"
  # AWS_DEPLOYMENT_ROLE_ARN: ${{ vars.AWS_DEV_DEPLOYMENT_ROLE_ARN }} --> Will need to update to above permission
  ENVIRONMENT: "stage"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEPLOYMENT_REGION }}
          audience: "sts.amazonaws.com"

      - name: Set up accounts and regions map
        run: |
          ACCOUNTS_AND_REGIONS='{"AWS_DEV_1":{"account_id":"${{ vars.AWS_DEV_ACCOUNT_ID }}","regions":["us-east-1"]}}'
          echo "ACCOUNTS_AND_REGIONS=$ACCOUNTS_AND_REGIONS" >> $GITHUB_ENV
      
      - name: Package Python Requirements
        run: |
          chmod +x scripts/package-python-requirements.sh
          ./scripts/package-python-requirements.sh

      - name: Upload CloudFormation Template
        run: |
          chmod +x scripts/upload-cloudformation-template.sh
          ./scripts/upload-cloudformation-template.sh

      - name: Create StackSet IAM Roles
        run: |
          # Create the administrator role
          aws cloudformation create-stack \
            --stack-name "cloudformation-stackset-admin-role" \
            --template-url "https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetAdministrationRole.yml" \
            --capabilities CAPABILITY_NAMED_IAM || true

          # Create the execution role
          aws cloudformation create-stack \
            --stack-name "cloudformation-stackset-execution-role" \
            --template-url "https://s3.amazonaws.com/cloudformation-stackset-sample-templates-us-east-1/AWSCloudFormationStackSetExecutionRole.yml" \
            --parameters ParameterKey=AdministratorAccountId,ParameterValue=${{ env.AWS_ADMIN_ACCOUNT_ID }} \
            --capabilities CAPABILITY_NAMED_IAM || true

          # Wait for roles to be created
          aws cloudformation wait stack-create-complete --stack-name "cloudformation-stackset-admin-role" || true
          aws cloudformation wait stack-create-complete --stack-name "cloudformation-stackset-execution-role" || true

      - name: Deploy CloudFormation StackSet
        run: |
          chmod +x scripts/deploy-cloudformation-stackset.sh
          ./scripts/deploy-cloudformation-stackset.sh
