name: Create Release

on:
  workflow_call:
    inputs:
      version_bump:
        type: string
        required: false
        default: 'patch'
        description: 'Version bump type (major, minor, patch)'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Bump version
        id: bump
        run: |
          if ! npm version ${{ inputs.version_bump }} -m "chore(release): %s [skip ci]"; then
            echo "Failed to bump version"
            exit 1
          fi
          NEW_VERSION=$(node -p "require('./package.json').version")
          if [ -z "$NEW_VERSION" ]; then
            echo "Failed to read new version"
            exit 1
          fi
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          commit-message: "chore(release): Bump version [skip ci]"
          title: "chore(release): Version bump"
          body: "Automated version bump"
          branch: "version-bump"
          base: "main"
          delete-branch: true
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          name: Release v${{ steps.bump.outputs.new_version }}
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ github.token }}
