name: Update Release Version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
        default: 'patch'
  push:
    branches:
      - stage

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    name: Bump NPM Version
    runs-on: ubuntu-latest
    if: github.ref_name == 'stage'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Configure Git and GitHub CLI
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Setup GitHub CLI
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          
      - name: Bump version and create PR
        run: |
          node scripts/update-release-version.js ${{ github.event_name == 'workflow_dispatch' && inputs.bump_type || 'patch' }}
          
      - name: Wait for PR creation and merge
        run: |
          # Wait for PR to be available (giving GitHub API time to process)
          sleep 10
          
          # Get the latest PR number
          PR_NUMBER=$(gh pr list --state open --base stage --json number --jq '.[0].number')
          
          if [ ! -z "$PR_NUMBER" ]; then
            # Enable auto-merge
            gh pr merge $PR_NUMBER --auto --merge
            echo "Pull request #$PR_NUMBER set to auto-merge"
          else
            echo "No open pull request found"
            exit 1
          fi
